server:
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  aop:
    proxy-target-class: true


mybatis:
#  mapper xml映射文件配置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lq.model
