server:
  port: 8080
spring:
  datasource:
    druid:
#      数据源访问配置
      url: jdbc:mysql://127.0.0.1:3306/devops?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: spdb1234